### ISSUE TITLE
Undefined if autocomplete is not defined with maeve-input

### ISSUE THREAD

**Issue by adityakakarot** [ateev/maeve#35]
* Undefined if autocomplete is not defined with maeve-input

### Usage

![screen shot 2017-03-06 at 9 13 29 pm](https://cloud.githubusercontent.com/assets/10103543/23617086/d1206994-02b1-11e7-8d2e-0b93edd77d26.png)

### Result

<img width="1025" alt="screen shot 2017-03-06 at 9 12 38 pm" src="https://cloud.githubusercontent.com/assets/10103543/23617103/e2e3b244-02b1-11e7-9952-5e2fa1ca9532.png">

**Comment by ateev** [comment]
Fixed
